[build]
  command = "npm run build"
  publish = "build"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Do not force the redirect for every request — leave Netlify able to
  # serve existing static files (assets) directly. For SPA fallback
  # we still return index.html for unknown routes but not for real
  # files such as /assets/*. This prevents returning index.html for
  # JS/CSS (which causes MIME type errors).
  force = false
